const { sqliteTable, text, real, integer } = require("drizzle-orm/sqlite-core");

const companies = sqliteTable("companies", {
  id: text("id").primaryKey(),
  companyName: text("company_name").notNull(),
  proprietor: text("proprietor").notNull(),
  address: text("address").notNull(),
  email: text("email").notNull(),
  phoneNumber: text("phone_number").notNull(),
  state: text("state").notNull(),
  city: text("city").notNull(),
  gstNumber: text("gst_number"),
  invoiceNumberInitial: text("invoice_number_initial").notNull(),
  logo: text("logo"),
  signature: text("signature"),
  accountNumber: text("account_number").notNull(),
  bankName: text("bank_name").notNull(),
  ifscCode: text("ifsc_code").notNull(),
  branch: text("branch").notNull(),
  revenueTotal: real("revenue_total").default(0),
  debt: real("debt").default(0),
  invoiceCount: integer("invoice_count").default(0),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

const clients = sqliteTable("clients", {
  id: text("id").primaryKey(),
  customerType: text("customer_type", { enum: ["business", "individual"] }).notNull(),
  salutation: text("salutation", { enum: ["mr", "ms", "mrs"] }),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  panNumber: text("pan_number"),
  companyName: text("company_name"),
  currency: text("currency").default("inr"),
  gstApplicable: integer("gst_applicable", { mode: "boolean" }).default(false),
  gstin: text("gstin"),
  stateCode: text("state_code"),
  billingCountry: text("billing_country"),
  billingState: text("billing_state"),
  billingCity: text("billing_city"),
  billingAddressLine1: text("billing_address_line1"),
  billingAddressLine2: text("billing_address_line2"),
  billingContactNo: text("billing_contact_no"),
  billingEmail: text("billing_email"),
  billingAlternateContactNo: text("billing_alternate_contact_no"),
  shippingCountry: text("shipping_country"),
  shippingState: text("shipping_state"),
  shippingCity: text("shipping_city"),
  shippingAddressLine1: text("shipping_address_line1"),
  shippingAddressLine2: text("shipping_address_line2"),
  shippingContactNo: text("shipping_contact_no"),
  shippingEmail: text("shipping_email"),
  shippingAlternateContactNo: text("shipping_alternate_contact_no"),
  balance: real("balance").default(0),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

const items = sqliteTable("items", {
  id: text("id").primaryKey(),
  itemName: text("item_name").notNull(),
  itemDescription: text("item_description"),
  hsnCode: text("hsn_code").notNull(),
  qtyAvailable: text("qty_available").notNull(),
  rate: text("rate").notNull(),
  unit: text("unit", { enum: ["kg", "meter", "piece", "litre", "bundle", "RFT"] }).notNull(),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

const invoices = sqliteTable("invoices", {
  id: text("id").primaryKey(),
  companyId: text("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  clientId: text("client_id").notNull().references(() => clients.id, { onDelete: "cascade" }),
  invoiceNumber: text("invoice_number").notNull().unique(),
  invoiceDate: text("invoice_date").notNull(),
  dueDate: text("due_date"),
  items: text("items").notNull(),
  subtotal: real("subtotal").notNull(),
  taxAmount: real("tax_amount").default(0),
  totalAmount: real("total_amount").notNull(),
  status: text("status", { enum: ["draft", "sent", "paid", "overdue"] }).default("draft"),
  notes: text("notes"),
  image: text("image"),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

const archives = sqliteTable("archives", {
  id: text("id").primaryKey(),
  originalId: text("original_id").notNull(),
  companyId: text("company_id").notNull(),
  clientId: text("client_id").notNull(),
  invoiceNumber: text("invoice_number").notNull(),
  invoiceDate: text("invoice_date").notNull(),
  dueDate: text("due_date"),
  items: text("items").notNull(),
  subtotal: real("subtotal").notNull(),
  taxAmount: real("tax_amount").default(0),
  totalAmount: real("total_amount").notNull(),
  status: text("status", { enum: ["draft", "sent", "paid", "overdue"] }).default("draft"),
  notes: text("notes"),
  image: text("image"),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
  archivedAt: text("archived_at").notNull(),
});

const dealers = sqliteTable("dealers", {
  id: text("id").primaryKey(),
  companyId: text("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  clientId: text("client_id").notNull().references(() => clients.id, { onDelete: "cascade" }),
  billNumber: text("bill_number").notNull(),
  billDate: text("bill_date").notNull(),
  billAmountTotal: real("bill_amount_total").notNull(),
  paymentMode: text("payment_mode", { enum: ["cash", "neft", "imps", "upi"] }).notNull(),
  referenceNumber: text("reference_number"),
  paymentStatus: text("payment_status", { enum: ["paid", "unpaid", "partial_paid"] }).notNull(),
  paidAmount: real("paid_amount").default(0),
  balanceAmount: real("balance_amount").default(0),
  description: text("description"),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

const dealerArchives = sqliteTable("dealer_archives", {
  id: text("id").primaryKey(),
  originalId: text("original_id").notNull(),
  companyId: text("company_id").notNull(),
  clientId: text("client_id").notNull(),
  billNumber: text("bill_number").notNull(),
  billDate: text("bill_date").notNull(),
  billAmountTotal: real("bill_amount_total").notNull(),
  paymentMode: text("payment_mode", { enum: ["cash", "neft", "imps", "upi"] }).notNull(),
  referenceNumber: text("reference_number"),
  paymentStatus: text("payment_status", { enum: ["paid", "unpaid", "partial_paid"] }).notNull(),
  paidAmount: real("paid_amount").default(0),
  balanceAmount: real("balance_amount").default(0),
  description: text("description"),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
  archivedAt: text("archived_at").notNull(),
});

const quotations = sqliteTable("quotations", {
  id: text("id").primaryKey(),
  companyId: text("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  clientId: text("client_id"),
  toPartyName: text("to_party_name"),
  toPartyAddress: text("to_party_address"),
  quotationId: text("quotation_id").notNull().unique(),
  subject: text("subject").notNull(),
  quotationDate: text("quotation_date").notNull(),
  items: text("items").notNull(),
  subtotal: real("subtotal").notNull(),
  totalAmount: real("total_amount").notNull(),
  termsAndConditions: text("terms_and_conditions"),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

const purchases = sqliteTable("purchases", {
  id: text("id").primaryKey(),
  invoiceNumber: text("invoice_number"),
  companyId: text("company_id").references(() => companies.id, { onDelete: "cascade" }),
  itemId: text("item_id").notNull().references(() => items.id, { onDelete: "cascade" }),
  clientId: text("client_id").notNull().references(() => clients.id, { onDelete: "cascade" }),
  quantity: real("quantity").notNull(),
  rate: real("rate").notNull(),
  amount: real("amount").notNull(),
  date: text("date").notNull(),
  createdAt: text("created_at"),
  updatedAt: text("updated_at"),
});

module.exports = {
  companies,
  clients,
  items,
  invoices,
  archives,
  dealers,
  dealerArchives,
  quotations,
  purchases,
};
